name: publish-public-doc

description: Steps to publish documentation page

inputs:
  token:
    description: github token
    required: true


runs:
  using: composite
  steps:
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: false
        installer-parallel: true
        virtualenvs-path: ./dst

    - name: Install dependencies with poetry
      shell: bash
      run: | 
        cd dst
        poetry install 
        pip install sphinx

    - name: Build Sphix Documentation
      shell: bash
      run: |
        cd dst
        make -C docs html 

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.token }}
        publish_dir: ./dst/docs/build/html