name: Checkout Project

description: Clean Workspace and checkout Project

inputs:
  release_public:
    description: If set to true, we prepare project to publish to public repository
    required: true
    default: "false"

runs:
  using: composite
  steps:

    - name: Build binary
      shell: bash
      run: | 
        echo "Is release ${{ inputs.release_public }} "
        make -C library hello 

    - name: Filter data
      shell: bash
      run: | 
        if [[ ${{ inputs.release_public }}  == 'true' ]]; then
          echo "Releasing to public" 
          rm -rf .git
        fi
    
        
        
        
