name: install-poetry

description: Steps to publish documentation page

inputs:
  working_directory:
    description: github token
    required: true
    default: ./


runs:
  using: composite
  steps:
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-path: "${{ inputs.working_directory }}/.venv"
        virtualenvs-in-project: true
        virtualenvs-create: true
        installer-parallel: true

    - name: Setup python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies with poetry
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      shell: bash
      run: | 
        cd ${{ inputs.working_directory }}
        poetry install 
        pip install sphinx