name: install-poetry

description: Steps to publish documentation page

inputs:
  working_directory:
    description: github token
    required: true
    default: ./


runs:
  using: composite
  steps:
    - name: Setup python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache-dependency-path: "**/poetry.lock"

    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-path: "${{ inputs.working_directory }}/.venv"
        virtualenvs-in-project: true
        virtualenvs-create: true
        installer-parallel: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: "${{ inputs.working_directory }}/.venv"
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies with poetry
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      shell: bash
      run: | 
        echo "Cached: ${{ steps.cached-poetry-dependencies.outputs.cache-hit }}"
        echo "Cache2: ${{steps.setup-python.outputs.cache-hit }}"
        cd ${{ inputs.working_directory }}
        poetry install 
        pip install sphinx