name: install-poetry

description: Steps to publish documentation page

inputs:
  working_directory:
    description: github token
    required: true
    default: "./"


runs:
  using: composite
  steps:
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-path: "${{ inputs.working_directory }}/.venv"
        virtualenvs-in-project: true
        virtualenvs-create: true
        installer-parallel: true

    - name: Install dependencies with poetry
      shell: bash
      run: | 
        cd ${{ inputs.working_directory }}
        poetry add bumpversion
        poetry install 
        echo "$(poetry env info)"
        pip install sphinx