name: conditional-release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-dev'
      - 'v[0-9]+.[0-9]+.[0-9]+.rc[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+.rc[0-9]+-dev'
      - 'v[0-9]+.[0-9]+.[0-9]+.alpha[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+.alpha[0-9]+-dev'
      - 'v[0-9]+.[0-9]+.[0-9]+.beta[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+.beta[0-9]+-dev'

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      is_release: ${{ steps.check-tag.outputs.is_release }}
    steps:
      - name: Check Tag
        id: check-tag
        run: |
          echo "is_release=false" >> "$GITHUB_OUTPUT"
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
           echo "is_release=true" >> "$GITHUB_OUTPUT"
          fi

  release-private:
    needs: tag
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare repository local
        id: prepare-repository-local
        uses: ./.github/actions/checkout-project
        with:
          release_public: "true"

      - name: Prepare ZIP asset
        run: |
          repo_name="${{ github.event.repository.name }}"
          echo "FILE_NAME=${{github.ref_name}}.zip" >> "$GITHUB_ENV"

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          body_path: README.md
          prerelease: false
          files: "${{env.FILE_NAME}}"
          token: ${{secrets.API_TOKEN_GITHUB}}
          tag_name: ${{ github.ref_name }}

#      - name: Prepare repository
#        id: prepare-repository
#        uses: ./.github/actions/checkout-project
#        with:
#          release_public: "true"
#
#      - name: Prepare ZIP asset
#        shell: bash
#        run: |
#          repo_name="${{ github.event.repository.name }}"
#          echo "FILE_NAME=${{github.ref_name}}.zip" >> "$GITHUB_ENV"
#          echo "done"


#  release-public:
#    needs: tag
#    if: ${{needs.tag.outputs.is_release == 'true' }}
#    permissions: write-all
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#        with:
#          repository: Temporary
#          ref: 'main'
#          token: $ {{ secrets.API_TOKEN_GITHUB }}
#
#      - name: Setup git config
#        run:
#          |
#          git config user.name "GitHub Actions Bot"
#          git config user.email "<>"


      - name: Push to Other Repository
        id: push-directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: .
          destination-github-username: "Farrukh-Olimov"
          destination-repository-name: "Temporary"
          user-email: olimov.farrukh@gmail.com
          target-branch: main
          create-target-branch-if-needed: true

            
        
    




