name: publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        uses: ./.github/actions/poetry-install

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          body_path: "CHANGELOG.md"
          token: ${{secrets.GITHUB_TOKEN}}
          tag_name: ${{ github.ref_name }}

      - name: Publish docs
        uses: ./.github/actions/publish-docs
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  update_main:
    needs: [release]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        uses: ./.github/actions/poetry-install

      - name: Move main to dev
        id: dev-next
        run: |
          echo "
          [bumpversion]
          current_version = $(poetry version --short)
          commit = False
          tag = False
          
          [bumpversion:file:pyproject.toml]
          search = version = "{current_version}"
          replace = version = "{new_version}"
                    
          [bumpversion:file:poetry_template/__init__.py]
          search = __version__ == '{current_version}'
          replace = __version__ == '{new_version}'          
          " > .bumpversion.cfg
          poetry run bumpversion --new-version $(poetry version --short) --allow-dirty --no-commit --no-tag --verbose 

      - name: Commit Changelog.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'move master to $(poetry version --short)'