name: publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        uses: ./.github/actions/poetry-install

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          body_path: CHANGELOG.md
          token: ${{secrets.GITHUB_TOKEN}}
          tag_name: ${{ github.ref_name }}

      - name: Publish docs
        uses: ./.github/actions/publish-docs
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move main to dev
        run: |
          source "$(poetry env info --path)/bin/activate"
          poetry version prerelease --verbose

      - name: Commit Changelog.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'move master to $(poetry version --short)'